name: umi-pipeline-nf
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python>=3.8
  - minimap2=2.24
  - samtools=1.15.1
  - seqtk=1.3
  - lofreq=2.1.5
  - freebayes=1.3.2
  - vcflib
  - bedtools=2.30.0
  - vsearch
  - varscan
  - medaka=1.7.0
  - openjdk=11.0.9
  - unzip=6.0
  - pip=22.2.2
  - pip:
    - catfishq==1.4.0
    - numpy==1.23.4
    - pysam==0.19.1
    - pandas==1.5.0
    - edlib==1.3.9

